apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp  
    spec:
      containers:
      - name: todo-app
        image: stolek/dotnet-todo-main:latest
        ports:
        - containerPort: 8080


