kind: Namespace
metadata:
  name: test-environment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp-deployment
  namespace: test-environment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp  
    spec:
      containers:
      - name: todo-app
        image: stolek/dotnet-todo-main:latest
        ports:
        - containerPort: 8080

apiVersion: v1
kind: Service
metadata:
  name: todoapp-svc
  namespace: test-environment
spec:
  selector:
    app: todoapp  
  type: NodePort
  ports:
    - protocol: TCP 
      port: 80
      targetPort: 8080
      nodePort: 30001
