name: CI
on:
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    name: build discover and deploy
    steps:
      - uses: actions/checkout@v2
      - name: Start minikube
        uses: medyagh/setup-minikube@latest
      # now you can run kubectl to see the pods in the cluster
      - name: Try the cluster!
        run: kubectl get pods -A
      - name: Deploy to minikube
        run: |
          kubectl apply -f deployment.yml
          kubectl apply -f service.yaml
      - name: Get resources in the namespace
        run: |
          kubectl get pods -A
          kubectl get svc -A  
      - name: Wait for Pod to be ready
        run: kubectl wait --for=condition=Ready pod/todoapp-pod --timeout=300s
      - name: Curl 
        run: |
          curl "$(kubectl get nodes -o wide | awk 'NR==2 {print $6}'):30001/todoitems"
          
