name: CI
on:
  - push
  - pull_request
jobs:
  job1:
    runs-on: ubuntu-latest
    name: build discover and deploy
    steps:
      - uses: actions/checkout@v2
      - name: Start minikube
        uses: medyagh/setup-minikube@latest
      # now you can run kubectl to see the pods in the cluster
      - name: Try the cluster!
        run: kubectl get pods -A
      - name: Deploy to minikube
        run: |
          kubectl apply -f deployment.yml
      - name: Get resources in the namespace
        run: kubectl get all  
      
      - name: Get Cluster IP
        run: |
         CLUSTER_IP=$(kubectl get svc -n $NAMESPACE $SERVICE_NAME -o jsonpath='{.spec.clusterIP}')
         echo "Cluster IP: $CLUSTER_IP"
        
      - name: Curl 
        run: |
          curl http://$CLUSTER_IP:30001/todoitems
          
